//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NameAndPlaceInfoApi
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class ApiPlaceInfoDBEntities : DbContext
    {
        public ApiPlaceInfoDBEntities()
            : base("name=ApiPlaceInfoDBEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<InfoTbl> InfoTbls { get; set; }
        public virtual DbSet<NameTbl> NameTbls { get; set; }
    }
}
