//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NameAndPlaceInfoApi
{
    using System;
    using System.Collections.Generic;
    
    public partial class InfoTbl
    {
        public int PlaceID { get; set; }
        public string InfoPlaceName { get; set; }
        public string Info { get; set; }
    }
}
