//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Domican_Stephen_S00209029_Web_Application_Project.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class PeopleAndPlacesDBEntities : DbContext
    {
        public PeopleAndPlacesDBEntities()
            : base("name=PeopleAndPlacesDBEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<PeopleTbl> PeopleTbl { get; set; }
        public virtual DbSet<PlacesTbl> PlacesTbl { get; set; }
    }
}
